# Generated by Django 5.1 on 2024-11-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('celular', models.PositiveSmallIntegerField()),
                ('sueldo', models.PositiveSmallIntegerField()),
                ('horario', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
